// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSApp.Data;

#nullable disable

namespace POSApp.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250516080604_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("POSApp.Core.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A001",
                            Name = "Water Bottle",
                            UnitPrice = 1.99m
                        },
                        new
                        {
                            Id = 2,
                            Code = "A002",
                            Name = "Notebook",
                            UnitPrice = 3.49m
                        },
                        new
                        {
                            Id = 3,
                            Code = "A003",
                            Name = "Pen",
                            UnitPrice = 0.99m
                        });
                });

            modelBuilder.Entity("POSApp.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "manager123",
                            Role = 0,
                            Username = "manager"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "cashier123",
                            Role = 1,
                            Username = "cashier1"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "cashier123",
                            Role = 1,
                            Username = "cashier2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
